import {
  FuturisticShelves,
  GlassTable,
  KingBed,
  LoungeChair,
  chicChair,
  contemporarySofa,
  cuttingEdgeBed,
  img1,
  img2,
  img3,
} from "../assets/images";
export const pages = [
  { page: "Home", url: "/" },
  { page: "About", url: "/about" },
  { page: "Products", url: "/products" },
  { page: "Cart", url: "/cart" },
  { page: "Checkout", url: "/checkout" },
  { page: "Orders", url: "/orders" },
];

export const feature = [
  { img: img1, name: "Avant-Garde Lamp", price: 179.99, id: 1 },
  { img: img2, name: "Coffee Table", price: 179.99, id: 3 },
  { img: img3, name: "Comfy Bed", price: 129.99, id: 4 },
];

export const products = [
  {
    id: 1,
    name: "Avant-Garde Lamp",
    brand: "Modenza",
    price: 179.99,
    color: ["bg-green-500", "bg-blue-500"],
    img: img1,
    category: "kids",
    freeShipping: false,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 2,
    name: "Chic Chair",
    brand: "Luxora",
    price: 339.99,
    color: ["bg-orange-500", "bg-green-500", "bg-blue-500"],
    img: chicChair,
    category: "chairs",
    freeShipping: true,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 3,
    name: "Coffee Table",
    brand: "Modenza",
    price: 179.99,
    color: ["bg-orange-500", "bg-yellow-500"],
    img: img2,
    category: "tables",
    freeShipping: false,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 4,
    name: "Comfy Bed",
    brand: "Homestead",
    price: 129.99,
    color: ["bg-orange-500"],
    img: img3,
    category: "beds",
    freeShipping: false,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 5,
    name: "Contemporary Sofa",
    brand: "Comfora",
    price: 159.99,
    color: ["bg-yellow-500"],
    img: contemporarySofa,
    category: "sofas",
    freeShipping: false,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 6,
    name: "Cutting-Edge Bed",
    brand: "Homestead",
    price: 84.99,
    color: ["bg-yellow-500", "bg-blue-500"],
    img: cuttingEdgeBed,
    category: "beds",
    freeShipping: true,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 7,
    name: "Futuristic Shelves",
    brand: "Luxora",
    price: 94.99,
    color: ["bg-green-500", "bg-yellow-500"],
    img: FuturisticShelves,
    category: "kids",
    freeShipping: true,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 8,
    name: "Glass Table",
    brand: "Modenza",
    price: 159.99,
    color: ["bg-orange-500", "bg-blue-500"],
    img: GlassTable,
    category: "tables",
    freeShipping: false,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 9,
    name: "King Bed",
    brand: "Homestead",
    price: 189.99,
    color: ["bg-orange-500"],
    img: KingBed,
    category: "beds",
    freeShipping: false,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 10,
    name: "Lounge Chair",
    brand: "Luxora",
    price: 259.99,
    color: ["bg-orange-500", "bg-green-500", "bg-blue-500"],
    img: LoungeChair,
    category: "chairs",
    freeShipping: false,
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
];
